import { Sparkles, GraduationCap, PenTool, LayoutGrid, FileText, Share2, Calculator, MessageSquare, Camera, Edit3, Heart, FileOutput, Scissors, Type, Zap } from 'lucide-react';
import { Helmet } from 'react-helmet-async';
import Hero from '../components/Hero';
import ToolCard from '../components/ToolCard';
import AdPlaceholder from '../components/AdPlaceholder';

const Home = () => {
    // ... (tools constant remains same)
    const tools = {
        ai: [
            { id: 'resume-analyzer', title: 'ATS Resume Checker', description: 'Analyze your resume against job descriptions with AI.', icon: FileText, colorClass: 'from-purple-600 to-blue-600', badge: 'Trending' },
            { id: 'notes-summarizer', title: 'AI Notes Summarizer', description: 'Transform long lectures into concise bullet points.', icon: Zap, colorClass: 'from-orange-500 to-red-500' },
            { id: 'chat-assistant', title: 'ClickForge Chat', description: 'AI assistant for all your study and productivity needs.', icon: MessageSquare, colorClass: 'from-blue-500 to-emerald-500' },
        ],
        viral: [
            { id: 'insta-bio', title: 'Instagram Bio Gen', description: 'Create viral Instagram bios that convert visitors.', icon: Camera, colorClass: 'from-pink-600 to-orange-500', badge: 'Popular' },
            { id: 'caption-gen', title: 'Viral Caption Gen', description: 'Generate engaging captions for TikTok, Insta, and FB.', icon: Edit3, colorClass: 'from-emerald-400 to-cyan-500' },
            { id: 'pickup-lines', title: 'AI Pickup Lines', description: 'Witty and smooth lines generated by AI.', icon: Heart, colorClass: 'from-red-600 to-pink-400' },
        ],
        utility: [
            { id: 'pdf-merge', title: 'PDF Merge/Compress', description: 'Quickly merge or compress your PDF documents.', icon: FileOutput, colorClass: 'from-red-500 to-rose-700' },
            { id: 'word-counter', title: 'Smart Word Counter', description: 'Deep analysis of your text for readability.', icon: Type, colorClass: 'from-slate-600 to-slate-800' },
        ],
        student: [
            { id: 'cgpa-calc', title: 'CGPA Calculator', description: 'Calculate your semester and cumulative GPA easily.', icon: Calculator, colorClass: 'from-indigo-600 to-purple-500' },
            { id: 'internships', title: 'Internship Tracker', description: 'Browse and track latest internship opportunities.', icon: GraduationCap, colorClass: 'from-emerald-600 to-teal-500' },
        ]
    };

    return (
        <div className="max-w-7xl mx-auto px-6">
            <Helmet>
                <title>ClickForge AI | Free AI & Student Productivity Tools</title>
                <meta name="description" content="Explore a collection of free AI tools for students and creators. ATS Resume Checker, Notes Summarizer, Viral Generators, and more." />
                <link rel="canonical" href="https://clickforge.ai/" />
            </Helmet>
            <Hero />

            <section id="trending" className="mt-20">
                <div className="flex items-center gap-3 mb-10">
                    <div className="w-10 h-1 h-px bg-blue-500"></div>
                    <h2 className="text-2xl font-bold">Trending Tools</h2>
                </div>
                <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-8">
                    {[...tools.ai, ...tools.viral].filter(t => t.badge).map(tool => (
                        <ToolCard key={tool.id} {...tool} />
                    ))}
                </div>
            </section>

            <AdPlaceholder type="banner" />

            <section id="ai-tools" className="mt-20">
                <h2 className="text-3xl font-bold mb-10 flex items-center gap-3 italic">
                    <Sparkles className="text-blue-400" /> AI-Powered Tools
                </h2>
                <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-8">
                    {tools.ai.map(tool => (
                        <ToolCard key={tool.id} {...tool} />
                    ))}
                </div>
            </section>

            <section id="viral-tools" className="mt-20">
                <h2 className="text-3xl font-bold mb-10 flex items-center gap-3 italic">
                    <PenTool className="text-pink-400" /> Viral Content Generators
                </h2>
                <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-8">
                    {tools.viral.map(tool => (
                        <ToolCard key={tool.id} {...tool} />
                    ))}
                </div>
            </section>

            <AdPlaceholder type="native" />

            <section id="student-tools" className="mt-20">
                <h2 className="text-3xl font-bold mb-10 flex items-center gap-3 italic">
                    <GraduationCap className="text-emerald-400" /> Student Utilities
                </h2>
                <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-8">
                    {tools.student.map(tool => (
                        <ToolCard key={tool.id} {...tool} />
                    ))}
                </div>
            </section>

            <section id="utility-tools" className="mt-20">
                <h2 className="text-3xl font-bold mb-10 flex items-center gap-3 italic">
                    <LayoutGrid className="text-slate-400" /> General Utilities
                </h2>
                <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-8">
                    {tools.utility.map(tool => (
                        <ToolCard key={tool.id} {...tool} />
                    ))}
                </div>
            </section>
        </div>
    );
};

export default Home;
