import React, { useState, useEffect } from 'react';
import { useParams, Link } from 'react-router-dom';
import { motion, AnimatePresence } from 'framer-motion';
import { Helmet } from 'react-helmet-async';
import { ChevronLeft, Sparkles, Send, Copy, Check, FileText, Zap, MessageSquare, Camera, Edit3, Heart, User } from 'lucide-react';
import api from '../utils/api';

const ToolDetails = () => {
    const { toolId } = useParams();
    const [input, setInput] = useState('');
    const [result, setResult] = useState('');
    const [loading, setLoading] = useState(false);
    const [copied, setCopied] = useState(false);

    const toolMetadata = {
        'humanizer': { id: 'humanizer', title: 'AI Plagiarism Humanizer', description: 'Transform AI-generated text into 100% human-sounding content that bypasses AI detectors.', icon: User, colorClass: 'from-blue-600 to-indigo-600' },
        'resume-analyzer': { id: 'resume-analyzer', title: 'ATS Resume Checker', description: 'Analyze your resume against job descriptions with AI.', icon: FileText, colorClass: 'from-purple-600 to-blue-600' },
        'notes-summarizer': { id: 'notes-summarizer', title: 'AI Notes Summarizer', description: 'Transform long lectures into concise bullet points.', icon: Zap, colorClass: 'from-orange-500 to-red-500' },
        'chat-assistant': { id: 'chat-assistant', title: 'Sigma Chat', description: 'AI assistant for all your study and productivity needs.', icon: MessageSquare, colorClass: 'from-blue-500 to-emerald-500' },
        'insta-bio': { id: 'insta-bio', title: 'Instagram Bio Gen', description: 'Create viral Instagram bios that convert visitors.', icon: Camera, colorClass: 'from-pink-600 to-orange-500' },
        'caption-gen': { id: 'caption-gen', title: 'Viral Caption Gen', description: 'Generate engaging captions for TikTok, Insta, and FB.', icon: Edit3, colorClass: 'from-emerald-400 to-cyan-500' },
        'pickup-lines': { id: 'pickup-lines', title: 'AI Pickup Lines', description: 'Witty and smooth lines generated by AI.', icon: Heart, colorClass: 'from-red-600 to-pink-400' },
    };

    const currentTool = toolMetadata[toolId] || toolMetadata['chat-assistant'];

    const handleGenerate = async () => {
        if (!input.trim()) return;
        setLoading(true);
        try {
            const apiResponse = await api.post('/tools/ai', {
                toolName: currentTool.title,
                input: input
            });
            setResult(apiResponse.data.result);
        } catch (err) {
            setResult('Error generating AI result. Please check your API key.');
        } finally {
            setLoading(false);
        }
    };

    const copyToClipboard = () => {
        navigator.clipboard.writeText(result);
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
    };

    return (
        <div className="max-w-4xl mx-auto px-6 py-12">
            <Helmet>
                <title>{currentTool.title} | Sigma AI 🧠💪</title>
                <meta name="description" content={currentTool.description} />
                <meta property="og:title" content={`${currentTool.title} - Sigma AI`} />
                <meta property="og:description" content={currentTool.description} />
                <link rel="canonical" href={`https://sigmaaitools.netlify.app/tool/${toolId}`} />
            </Helmet>

            <Link to="/" className="inline-flex items-center gap-2 text-slate-500 hover:text-blue-500 transition-colors mb-8 font-bold uppercase text-xs tracking-widest">
                <ChevronLeft size={16} /> Back to Dashboard
            </Link>

            <div className="glass rounded-[2.5rem] p-10 relative overflow-hidden">
                <div className={`absolute top-0 right-0 w-64 h-64 bg-gradient-to-br ${currentTool.colorClass} opacity-10 blur-[80px] pointer-events-none`}></div>

                <div className="flex items-center gap-6 mb-10 relative z-10">
                    <div className={`w-20 h-20 rounded-3xl flex items-center justify-center p-5 bg-gradient-to-br ${currentTool.colorClass} shadow-2xl`}>
                        <currentTool.icon size={40} className="text-white" />
                    </div>
                    <div>
                        <h1 className="text-4xl font-black tracking-tight uppercase italic">{currentTool.title}</h1>
                        <p className="text-[var(--text-secondary)] font-medium italic">Powered by Sigma AI Engine</p>
                    </div>
                </div>

                <div className="space-y-6 relative z-10">
                    <div className="space-y-2">
                        <label className="text-xs font-black uppercase tracking-widest text-slate-500 ml-2">Input Content</label>
                        <textarea
                            value={input}
                            onChange={(e) => setInput(e.target.value)}
                            placeholder={`Paste your content here for ${currentTool.title}...`}
                            className="w-full h-48 bg-black/5 dark:bg-white/5 border border-white/10 rounded-3xl p-6 focus:ring-2 focus:ring-blue-500/50 outline-none transition-all resize-none text-lg font-medium"
                        />
                    </div>

                    <button
                        onClick={handleGenerate}
                        disabled={loading || !input.trim()}
                        className="w-full py-5 bg-gradient-to-r from-blue-600 to-emerald-500 rounded-2xl text-xl font-black text-white hover:shadow-[0_0_30px_rgba(59,130,246,0.3)] transition-all flex items-center justify-center gap-3 disabled:opacity-50"
                    >
                        {loading ? (
                            <motion.div
                                animate={{ rotate: 360 }}
                                transition={{ repeat: Infinity, duration: 1, ease: "linear" }}
                            >
                                <Zap size={24} />
                            </motion.div>
                        ) : (
                            <>GENERATE MAGIC <Sparkles size={24} /></>
                        )}
                    </button>
                </div>

                <AnimatePresence>
                    {result && (
                        <motion.div
                            initial={{ opacity: 0, y: 20 }}
                            animate={{ opacity: 1, y: 0 }}
                            className="mt-12 p-8 bg-blue-500/5 dark:bg-blue-400/5 border border-blue-500/20 rounded-3xl relative"
                        >
                            <div className="flex justify-between items-center mb-6">
                                <span className="text-xs font-black uppercase tracking-widest text-blue-500">AI Human Result</span>
                                <button
                                    onClick={copyToClipboard}
                                    className="p-2.5 rounded-xl glass hover:bg-blue-500/10 transition-all flex items-center gap-2 text-blue-500"
                                >
                                    {copied ? <Check size={18} /> : <Copy size={18} />}
                                    <span className="text-xs font-black uppercase">Copy Result</span>
                                </button>
                            </div>
                            <div className="prose prose-invert max-w-none whitespace-pre-wrap leading-relaxed font-medium">
                                {result}
                            </div>
                        </motion.div>
                    )}
                </AnimatePresence>
            </div>
        </div>
    );
};

export default ToolDetails;
